version: '3.8'

services:
  # Next.js Application
  noteflow-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: noteflow-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CONVEX_DEPLOYMENT=${CONVEX_DEPLOYMENT}
      - NEXT_PUBLIC_CONVEX_URL=${NEXT_PUBLIC_CONVEX_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/login
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/register
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/workspace
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/workspace
    networks:
      - noteflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - convex-dev

  # Convex Development Server (local instance)
  convex-dev:
    image: node:20-alpine
    container_name: noteflow-convex
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npx convex dev --once && tail -f /dev/null"
    environment:
      - CONVEX_DEPLOYMENT=${CONVEX_DEPLOYMENT}
    networks:
      - noteflow-network
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.convex/deployment_config.json"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  noteflow-network:
    driver: bridge

volumes:
  node_modules:
  next_cache:
